// schema-dump prints the SQLite DDL for all Bifrost configstore tables.
// Regenerate docs/database-schema.sql with:
//
//	go run ./tests/scripts/schema-dump/main.go > docs/database-schema.sql
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/maximhq/bifrost/framework/configstore/tables"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func main() {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "open sqlite: %v\n", err)
		os.Exit(1)
	}

	models := []any{
		&tables.TableFeatureFlag{},
		&tables.TableBudget{},
		&tables.TableRateLimit{},
		&tables.TableProvider{},
		&tables.TableKey{},
		&tables.TableModel{},
		&tables.TableOauthConfig{},
		&tables.TableOauthToken{},
		&tables.TableMCPClient{},
		&tables.TableClientConfig{},
		&tables.TableEnvKey{},
		&tables.TableVectorStoreConfig{},
		&tables.TableLogStoreConfig{},
		&tables.TableCustomer{},
		&tables.TableTeam{},
		&tables.TableVirtualKey{},
		&tables.TableGovernanceConfig{},
		&tables.TablePricingOverride{},
		&tables.TablePlugin{},
		&tables.TableVirtualKeyProviderConfig{},
		&tables.TableVirtualKeyMCPConfig{},
		&tables.TableFrameworkConfig{},
		&tables.SessionsTable{},
		&tables.TableVirtualKeyProviderConfigKey{},
		&tables.TableRoutingRule{},
		&tables.TableFolder{},
		&tables.TablePrompt{},
		&tables.TablePromptVersion{},
		&tables.TablePromptVersionMessage{},
		&tables.TablePromptSession{},
		&tables.TablePromptSessionMessage{},
		&tables.TableOauthUserSession{},
		&tables.TableOauthUserToken{},
		&tables.TableDistributedLock{},
		&tables.TableAccessKeyToken{},
	}
	if err := db.AutoMigrate(models...); err != nil {
		fmt.Fprintf(os.Stderr, "auto migrate: %v\n", err)
		os.Exit(1)
	}
	if err := db.SetupJoinTable(&tables.TableVirtualKeyProviderConfig{}, "Keys", &tables.TableVirtualKeyProviderConfigKey{}); err != nil {
		fmt.Fprintf(os.Stderr, "setup join table: %v\n", err)
		os.Exit(1)
	}

	type tableRow struct {
		Name string
		SQL  string
	}
	var rows []tableRow
	if err := db.Raw(`
		SELECT name, sql
		FROM sqlite_master
		WHERE type = 'table'
		  AND name NOT LIKE 'sqlite_%'
		ORDER BY name
	`).Scan(&rows).Error; err != nil {
		fmt.Fprintf(os.Stderr, "read schema: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("-- Bifrost configstore schema (generated by tests/scripts/schema-dump)")
	fmt.Println("-- Do not edit manually; regenerate with:")
	fmt.Println("--   go run ./tests/scripts/schema-dump/main.go > docs/database-schema.sql")
	fmt.Println()

	for _, row := range rows {
		if row.SQL == "" {
			continue
		}
		fmt.Println(strings.TrimSpace(row.SQL) + ";")
		fmt.Println()
	}
}
