package tables

import "time"

// TableAccessKeyToken is the GORM model for the `access_key_token` table managed
// by the mpilotv2 backend. It lives in each tenant's own database.
//
// The primary key (access_key) is a UUID generated by the backend and embedded
// in every JWT issued to a user of that tenant. The gateway uses this table to
// validate that the credential is still active and has not expired.
//
// Java source: com.monetize360.mpillotv2.common.model.tenants.AccessKeyToken
type TableAccessKeyToken struct {
	// AccessKey is the UUID primary key, generated by the backend.
	// It is embedded in the JWT as the "accessKey" claim.
	AccessKey string `gorm:"column:access_key;primaryKey;type:varchar(36)" json:"access_key"`

	// Name is a human-readable label for the credential (e.g. "CI Token").
	Name string `gorm:"column:name;not null" json:"name"`

	// ExpiresAt is when the access key becomes invalid.
	ExpiresAt time.Time `gorm:"column:expires_at;not null" json:"expires_at"`

	// IsActive controls whether the key can be used. Revoked keys have false.
	IsActive bool `gorm:"column:is_active;not null;default:true" json:"is_active"`

	// UserID is the UUID of the user who owns this credential.
	UserID string `gorm:"column:user_id;not null;type:varchar(36);index" json:"user_id"`

	// Audit timestamps (populated by the backend's BaseEntity).
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName overrides the GORM default so the correct table is targeted.
func (TableAccessKeyToken) TableName() string { return "access_key_token" }
